pipeline {
    agent any

    tools {
        nodejs 'node-20'
    }

    environment {
        sonarHome = tool 'sonar-scanner'
        imageName = 'sanketdesai09/frontend'
        DOCKER_CREDS = credentials('dockerhub-creds')
        GITHUB_TOKEN = credentials('github-token')
    }

    stages {

        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }

        stage('checkout code') {
            steps {
                checkout scm
            }
        }

        stage('Set image tag') {
            steps {
                script {
                    env.IMAGE_TAG = sh(
                        script: "git rev-parse --short HEAD",
                        returnStdout: true
                    ).trim()
                }
                echo "Using image tag: ${IMAGE_TAG}"
            }
        }

        stage('install dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm ci'
                }
            }
        }

        stage('sonarqube analysis') {
            steps {
                dir('frontend') {
                    withSonarQubeEnv('sonarqube') {
                        sh """
                        ${sonarHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=frontend \
                        -Dsonar.projectName=frontend \
                        -Dsonar.sources=.
                        """
                    }
                }
            }
        }

        stage('docker build') {
          steps {
            dir('frontend') {
              sh """
              commitHash=\$(git rev-parse --short HEAD)
        
              docker build -t ${imageName}:\$commitHash .
              docker tag ${imageName}:\$commitHash ${imageName}:latest
              """
            }
          }
        }

        stage('trivy image scan') {
            steps {
                sh """
                docker run --rm \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  -v \$HOME/.cache/trivy:/root/.cache/trivy \
                  aquasec/trivy:latest \
                  image --severity HIGH,CRITICAL --exit-code 0 \
                  --format table \
                  ${imageName}:latest
                """
            }
        }

        stage('push image to dockerhub') {
            when {
                branch 'main'
            }
            steps {
                sh """
                echo "$DOCKER_CREDS_PSW" | docker login -u "$DOCKER_CREDS_USR" --password-stdin
                docker push ${imageName}:${IMAGE_TAG}
                docker push ${imageName}:latest
                """
            }
        }

        stage('Update GitOps manifests repo') {
            when {
                branch 'main'
            }
            steps {
                sh """
                rm -rf shop-platform-gitops

                git clone https://x-access-token:${GITHUB_TOKEN}@github.com/dev-sd092/shop-platform-gitops.git
                cd shop-platform-gitops

                sed -i 's|image: .*frontend:.*|image: ${imageName}:${IMAGE_TAG}|g' environments/dev/frontend.yaml

                git config user.name "jenkins"
                git config user.email "jenkins@ci.local"

                git add environments/dev/frontend.yaml
                git commit -m "Update frontend image to ${IMAGE_TAG}"
                git push origin main
                """
            }
        }
    }
}
