pipeline {
    agent any

    tools {
        nodejs 'node-20'
    }

    environment {
        sonarHome = tool 'sonar-scanner'
        imageName = 'sanketdesai09/frontend'
        DOCKER_CREDS = credentials('dockerhub-creds')
    }

    stages {

        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }

        stage('checkout code') {
            steps {
                checkout scm
            }
        }

        stage('install dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm ci'
                }
            }
        }

        stage('sonarqube analysis') {
            steps {
                dir('frontend') {
                    withSonarQubeEnv('sonarqube') {
                        sh """
                        ${sonarHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=frontend \
                        -Dsonar.projectName=frontend \
                        -Dsonar.sources=.
                        """
                    }
                }
            }
        }

        stage('docker build') {
          steps {
            dir('frontend') {
              sh """
              commitHash=\$(git rev-parse --short HEAD)
        
              docker build -t ${imageName}:\$commitHash .
              docker tag ${imageName}:\$commitHash ${imageName}:latest
              """
            }
          }
        }

        stage('trivy image scan') {
            steps {
                sh """
                docker run --rm \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  -v \$HOME/.cache/trivy:/root/.cache/trivy \
                  aquasec/trivy:latest \
                  image --severity HIGH,CRITICAL --exit-code 0 \
                  --format table \
                  ${imageName}:latest
                """
            }
        }

        stage('push image to dockerhub') {
            when {
                branch 'main'
            }
            steps {
                sh """
                echo "$DOCKER_CREDS_PSW" | docker login -u "$DOCKER_CREDS_USR" --password-stdin
                docker push ${imageName}:latest
                """
            }
        }
    }
}
