pipeline{
    agent any

    tools{
        nodejs 'node-20'
    }

    environment{
        imageName = 'sanketdesai09/cart-service'
        scannerHome = tool 'sonar-scanner'
        dcHome = tool 'OWASP-DC'
        DOCKER_CREDS = credentials('dockerhub-creds')
        GITHUB_TOKEN = credentials('github-token')
    }

    stages{
        stage('cleanup workspace'){
            steps{
                cleanWs()
            }
        }

        stage('checkout code'){
            steps{
                checkout scm
            }
        }

        stage('install dependencies'){
            steps{
                dir('cart-service'){
                    sh 'npm ci'
                }
            }
        }

        stage('Set image tag') {
            steps {
                script {
                    env.IMAGE_TAG = sh(
                        script: "git rev-parse --short HEAD",
                        returnStdout: true
                    ).trim()
                }
                echo "Using image tag: ${IMAGE_TAG}"
            }
        }

        stage('sonarqube analysis'){
            steps{
                dir('cart-service'){
                    withSonarQubeEnv('sonarqube'){
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectName=cart-service \
                        -Dsonar.projectKey=cart-service \
                        -Dsonar.sources=. 
                        """
                    }
                }
            }
        }

        stage('quality gates check'){
            steps{
                timeout(time: 10, unit:'MINUTES'){
                    waitForQualityGate abortPipeline:true
                }
            }
        }

        stage('owasp dependency check'){
            steps{
                dir('cart-service'){
                    sh """
                    ${dcHome}/bin/dependency-check.sh \
                    --project cart-service \
                    --scan . \
                    --format XML \
                    --out dependency-check-report \
                    --disableAssembly \
                    --disableYarnAudit
                    """
                }
            }
        }

        stage('docker build'){
            steps{
                dir('cart-service'){
                    sh """
                        commitHash=\$(git rev-parse --short HEAD)

                        docker build -t ${imageName}:\$commitHash .
                        docker tag ${imageName}:\$commitHash ${imageName}:latest
                    """
                }
            }
        }

        stage('trivy image scan'){
            steps{
                dir('cart-service'){
                    sh """
                    docker run --rm \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    -v \$HOME/.cache/trivy:/root/.cache/trivy \
                    aquasec/trivy:latest \
                    image --severity HIGH,CRITICAL --exit-code 0 \
                    --format table \
                    ${imageName}:latest
                    """
                }
            }
        }

        stage('push image to dockerhub') {
            when {
                branch 'main'
            }
            steps {
                sh """
                echo "$DOCKER_CREDS_PSW" | docker login -u "$DOCKER_CREDS_USR" --password-stdin
                docker push ${imageName}:${IMAGE_TAG}
                docker push ${imageName}:latest
                """
            }
        }

        stage('Update GitOps manifests repo') {
            when {
                branch 'main'
            }
            steps {
                sh """
                rm -rf shop-platform-gitops

                git clone https://x-access-token:${GITHUB_TOKEN}@github.com/dev-sd092/shop-platform-gitops.git
                cd shop-platform-gitops

                sed -i 's|image: .*frontend:.*|image: ${imageName}:${IMAGE_TAG}|g' environments/dev/cart-service.yaml

                git config user.name "jenkins"
                git config user.email "jenkins@ci.local"

                git add environments/dev/cart-service.yaml
                git commit -m "Update cart service image to ${IMAGE_TAG}"
                git push origin main
                """
            }
        }
    }
}