pipeline{
    agent any 

    tools{
        nodejs 'node-20'
    }

    environment{
        imageName = 'sanketdesai09/order-service'
        scannerHome = tool 'sonar-scanner'
        dcHome = tool 'OWASP-DC'
        DOCKER_CREDS = credentials('dockerhub-creds')
        GITHUB_TOKEN = credentials('github-token')
    }

    stages{
        stage('cleanup workspace'){
            steps{
                cleanWs()
            }
        }

        stage('code checkout'){
            steps{
                checkout scm
            }
        }

        stage('install dependencies'){
            steps{
                dir('order-service'){
                    sh 'npm ci'
                }
            }
        }

        stage('Set image tag') {
            steps {
                script {
                    env.IMAGE_TAG = sh(
                        script: "git rev-parse --short HEAD",
                        returnStdout: true
                    ).trim()
                }
                echo "Using image tag: ${IMAGE_TAG}"
            }
        }

        stage('sonarQube scanner check'){
            steps{
                dir('order-service'){
                    withSonarQubeEnv('sonarqube'){
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectName=order-service \
                        -Dsonar.projectKey=order-service \
                        -Dsonar.sources=. \
                        """
                    }
                }
            }
        }

        stage('quality gate checks'){
            steps{
                timeout(time: 10, unit:'MINUTES'){
                    waitForQualityGate abortPipeline:true
                }
            }
        }

        stage('dependency check - OWASP'){
            steps{
                dir('order-service'){
                    sh """
                    ${dcHome}/bin/dependency-check.sh \
                    --project order-service \
                    --scan . \
                    --format XML \
                    --out dependency-check-report \
                    --disableAssembly \
                    --disableYarnAudit
                    """
                }
            }
        }

        stage('docker build'){
            steps{
                dir('order-service'){
                    sh """
                    commitHash=\$(git rev-parse --short HEAD)

                    docker build -t ${imageName}:\$commitHash .
                    docker tag ${imageName}:\$commitHash ${imageName}:latest
                    """
                }
            }
        }

        stage('trivy image scan'){
            steps{
                sh """
                docker run --rm \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v \$HOME/.cache/trivy:/root/.cache/trivy \
                aquasec/trivy:latest \
                image --severity HIGH,CRITICAL --exit-code 0 \
                --format table \
                ${imageName}:latest
                """
            }
        }

        stage('push image to dockerhub') {
            when {
                branch 'main'
            }
            steps {
                sh """
                echo "$DOCKER_CREDS_PSW" | docker login -u "$DOCKER_CREDS_USR" --password-stdin
                docker push ${imageName}:${IMAGE_TAG}
                docker push ${imageName}:latest
                """
            }
        }

        stage('Update GitOps manifests repo') {
            when { branch 'main' }
            steps {
                withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    rm -rf shop-platform-gitops

                    git clone https://x-access-token:$GITHUB_TOKEN@github.com/dev-sd092/shop-platform-gitops.git
                    cd shop-platform-gitops

                    sed -i "s|image: .*product-service:.*|image: sanketdesai09/order-service:${IMAGE_TAG}|g" environments/dev/order-service.yaml

                    git config user.name "jenkins"
                    git config user.email "jenkins@ci.local"

                    git add environments/dev/order-service.yaml
                    git commit -m "Update order service image to ${IMAGE_TAG}" || echo "No changes to commit"
                    git push origin main
                    '''
                }
            }
        }
    }
}