pipeline{
    agent any 

    tools{
        nodejs 'node-20'
    }

    environment{
        imageName = 'sanketdesai09/order-service'
        scannerHome = tool 'sonar-scanner'
        dcHome = tool 'OWASP-DC'
    }

    stages{
        stage('cleanup workspace'){
            steps{
                cleanWs()
            }
        }

        stage('code checkout'){
            steps{
                checkout scm
            }
        }

        stage('install dependencies'){
            steps{
                dir('order-service'){
                    sh 'npm ci'
                }
            }
        }

        stage('sonarQube scanner check'){
            steps{
                dir('order-service'){
                    withSonarQubeEnv('sonarqube'){
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectName=order-service \
                        -Dsonar.projectKey=order-service \
                        -Dsonar.sources=. \
                        """
                    }
                }
            }
        }

        stage('quality gate checks'){
            steps{
                timeout(time: 10, unit:'MINUTES'){
                    waitForQualityGate abortPipeline:true
                }
            }
        }

        stage('dependency check - OWASP'){
            steps{
                dir('order-service'){
                    sh """
                    ${dcHome}/bin/dependency-check.sh \
                    --project order-service \
                    --scan . \
                    --format XML \
                    --out dependency-check-report \
                    --disableAssembly \
                    --disableYarnAudit
                    """
                }
            }
        }

        stage('docker build'){
            steps{
                dir('order-service'){
                    sh """
                    commitHash=\$(git rev-parse --short HEAD)

                    docker build -t ${imageName}:\$commitHash .
                    docker tag ${imageName}:\$commitHash ${imageName}:latest
                    """
                }
            }
        }

        stage('trivy image scan'){
            steps{
                sh """
                docker run --rm \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v \$HOME/.cache/trivy:/root/.cache/trivy \
                aquasec/trivy:latest \
                image --severity CRITICAL --exit-code 1 \
                --format table \
                ${imageName}:latest
                """
            }
        }

        stage('image push'){
            when{
                branch 'main'
            }

            steps{
                script{
                    docker.withRegistry('https://index.docker.io','dockerhub-creds'){
                        docker.image("${imageName}:latest").push()
                    }
                }
            }
        }
    }
}