pipeline {
  agent any

  tools {
    nodejs 'node-20'
  }

  environment {
    imageName = 'sanketdesai09/auth-service'
    scannerHome = tool 'sonar-scanner'
    dcHome = tool 'OWASP-DC'
    DOCKER_CREDS = credentials('dockerhub-creds')
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('auth-service') {
          sh 'npm ci'
        }
      }
    }
      
    stage('Static Code Analysis - SonarQube') {
      steps {
        dir('auth-service') {
          withSonarQubeEnv('sonarqube') {
              sh """
              ${scannerHome}/bin/sonar-scanner \
              -Dsonar.projectName=auth-service \
              -Dsonar.projectKey=auth-service \
              -Dsonar.sources=.
              """
          }
        }
      }
    }

    stage('Dependency Scan - OWASP') {
      steps {
        dir('auth-service') {
          sh """
            ${dcHome}/bin/dependency-check.sh \
              --project auth-service \
              --scan . \
              --format XML \
              --out dependency-check-report \
              --disableAssembly \
              --disableYarnAudit
          """
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('auth-service'){
            sh """
              commitHash=\$(git rev-parse --short HEAD)

              docker build -t ${imageName}:\$commitHash .
              docker tag ${imageName}:\$commitHash ${imageName}:latest
            """
          }
        }
      }

    stage('Image Scan - Trivy') {
      steps {
        sh """
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v \$HOME/.cache/trivy:/root/.cache/trivy \
            aquasec/trivy:latest \
            image --severity HIGH,CRITICAL --exit-code 0 \
            --format table \
            $imageName:latest
        """
      }
    }

    stage('Push Image') {
      when {
        branch 'main'
      }
      
      steps{
         sh """
          echo "$DOCKER_CREDS_PSW" | docker login -u "$DOCKER_CREDS_USR" --password-stdin
          docker push ${imageName}:latest
          """
      }
    }
  }
}
