pipeline {
  agent any

  tools {
    nodejs 'node-20'
    'hudson.plugins.sonar.SonarRunnerInstallation' 'sonar-scanner'
  }

  environment {
    REGISTRY = 'docker.io'
    IMAGE_NAME = 'sanketdesai09/auth-service'
    SONAR_HOST_URL = 'http://localhost:9000'
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('auth-service') {
          sh 'npm ci'
        }
      }
    }
      
    stage('Static Code Analysis - SonarQube') {
      steps {
        dir('auth-service') {
          script {
            def scannerHome = tool 'sonar-scanner'
            
            withSonarQubeEnv('sonarqube') {
                sh "${scannerHome}/bin/sonar-scanner \
                -Dsonar.projectKey=auth-service \
                -Dsonar.sources=. \
                -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info"
            }
          }
        }
      }
    }

    stage('Dependency Scan - OWASP') {
      steps {
        dir('auth-service') {
          script {
            def dcHome = tool 'OWASP-DC'

            sh """
              ${dcHome}/bin/dependency-check.sh \
                --project auth-service \
                --scan . \
                --format XML \
                --out dependency-check-report \
                --disableAssembly
            """
          }
        }
      }
    }


    stage('Build Application') {
      steps {
        dir('auth-service') {
          sh 'npm run build  || echo "No build step for backend"'
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('auth-service'){
          script {
            def commitHash = sh(
              script: 'git rev-parse --short HEAD',
              returnStdout: true
            ).trim()

            sh """
              docker build -t $IMAGE_NAME:${commitHash} .
              docker tag $IMAGE_NAME:${commitHash} $IMAGE_NAME:latest
            """
          }
        }
      }
    }

    stage('Image Scan - Trivy') {
      steps {
        sh """
          trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE_NAME:latest
        """
      }
    }

    stage('Push Image') {
      when {
        branch 'main'
      }
      environment {
        DOCKER_CREDS = credentials('dockerhub-creds')
      }
      steps {
        sh """
          echo $DOCKER_CREDS_PSW | docker login -u $DOCKER_CREDS_USR --password-stdin
          docker push $IMAGE_NAME:latest
        """
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
